name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  # ROS2 Humbleに合わせ、3.10に絞るのが安全です
    steps:
      - uses: actions/checkout@v3
      - name: All test
        run: |
          chmod +x ./test.bash
          ./test.bash
